import scikitplot as skplt
import matplotlib.pyplot as plt

y_true = [2, 0, 2, 2, 0, 1] # ground truth labels
y_probas = [[0.1,0.4,0.5], [0.3,0.2,0.5], [0.9,0.0,0.1], [0.2,0.2,0.6], [0.1,0.1,0.8], [0.1,0.9,0.0]] # predicted probabilities generated by sklearn classifier
skplt.metrics.plot_roc_curve(y_true, y_probas)
plt.show()
